[features]
resolution = true
skip-lint = false

[programs.localnet]
proofmesh_guard = "Guard111111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = ".anchor/test-wallet.json"

[test.validator]
rpc_port = 18897
faucet_port = 19901
ledger = ".anchor/test-ledger"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.anchor.json -t 1000000 programs/proofmesh_guard/tests/**/*.test.ts"
